version: "3.8"

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  sales-gateway:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: sales-gateway
    command: npm start
    environment:
      - SERVER_PORT=8081
    ports:
      - 8081:8081
    volumes:
      - ../microservices/sales-gateway:/app
    links:
      - users-manager
      - products-manager
      - sales-manager

  sales-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: sales-manager
    command: npm start
    environment:
      - SERVER_PORT=8082
    links:
      - redis
      - users-manager
      - products-manager
    volumes:
      - ../microservices/sales-manager:/app
  
  users-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: users-manager
    command: npm start
    environment:
      - SERVER_PORT=8083
    links:
      - redis
    volumes:
      - ../microservices/users-manager:/app
  
  products-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: products-manager
    command: npm start
    environment:
      - SERVER_PORT=8084
    links:
      - redis
    volumes:
      - ../microservices/products-manager:/app
  
  redis:
    image: redis:alpine
    container_name: redis