version: "3.8"

services:
  sales-gateway:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: sales-gateway
    command: npm run start:dev
    environment:
      - SERVER_PORT=8081
    ports:
      - 8081:8081
    volumes:
      - ../microservices/sales-gateway:/app
    links:
      - users-manager
      - sales-manager
      - products-manager

  sales-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: sales-manager
    command: npm run start:dev
    environment:
      - SERVER_PORT=8082
    links:
      - mysql
      - users-manager
      - products-manager
    volumes:
      - ../microservices/sales-manager:/app
  
  users-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: users-manager
    command: npm run start:dev
    environment:
      - SERVER_PORT=8083
      - DB_PASSWORD=root
    links:
      - mysql
    volumes:
      - ../microservices/users-manager:/app
  
  products-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: products-manager
    command: npm run start:dev
    environment:
      - SERVER_PORT=8084
    links:
      - mysql
    volumes:
      - ../microservices/products-manager:/app
  
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql