version: "3.8"

services:
  sales-gateway:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: sales-gateway
    environment:
      - SERVER_PORT=8081
    ports:
      - 8081:8081
    expose:
      - 8081
    volumes:
      - ../microservices/sales-gateway:/app
    command: npm run start:dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.sales.rule=Host(`sales.localhost`)
      - traefik.http.routers.sales.entrypoints=web
    links:
      - users-manager

  sales-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: sales-manager
    environment:
      - SERVER_PORT=8082
    ports:
      - 8082:8082
    expose:
      - 8082
    links:
      - mysql
    volumes:
      - ../microservices/sales-manager:/app
    command: npm run start:dev
  
  users-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: users-manager
    environment:
      - SERVER_PORT=8083
      - DB_PASSWORD=root
    ports:
      - 8083:8083
    expose:
      - 8083
    links:
      - mysql
    volumes:
      - ../microservices/users-manager:/app
    command: npm run start:dev
  
  products-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    container_name: products-manager
    environment:
      - SERVER_PORT=8084
    ports:
      - 8084:8084
    expose:
      - 8084
    links:
      - mysql
    volumes:
      - ../microservices/products-manager:/app
    command: npm run start:dev
  
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
  
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql