version: "3.8"

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  sales-gateway:
    image: 'docker.io/bitnami/node:14-debian-10'
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    expose:
      - "8081"
    volumes:
      - ../microservices/sales-gateway:/app
    command: "npm start"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sales.rule=Host(`sales.localhost`)"
      - "traefik.http.routers.sales.entrypoints=web"

  sales-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    environment:
      - SERVER_PORT=8082
    ports:
      - "8082:8082"
    expose:
      - "8082"
    volumes:
      - ../microservices/sales-manager:/app
    command: "npm start"
  
  users-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    environment:
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    expose:
      - "8083"
    volumes:
      - ../microservices/users-manager:/app
    command: "npm start"
  
  products-manager:
    image: 'docker.io/bitnami/node:14-debian-10'
    environment:
      - SERVER_PORT=8084
    ports:
      - "8084:8084"
    expose:
      - "8084"
    volumes:
      - ../microservices/products-manager:/app
    command: "npm start"